### ISSUE TITLE
Conflict with Makefile support plugin

### ISSUE THREAD

**Issue by LGLTeam** [intuit/DockDockBuild#30]
**Is this a bug report, or a feature request?** Bug report

**What is the current behavior?**
Causing whole Android Studio to do nothing like a useless program and causing freezing when trying to open settings

```
com.intellij.diagnostic.PluginException: Trying to override already registered file type Makefile [Plugin: name.kropp.intellij.makefile]
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.loadFileTypeBeans(FileTypeManagerImpl.java:422)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:310)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.<init>(FileTypeManagerImpl.java:222)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:660)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:54)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$future$1.run(ComponentManagerImpl.kt:802)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Install both DockDockBuild and Makefile support plugins https://plugins.jetbrains.com/plugin/9333-makefile-support (Some time Android Studio ask to install DockDockBuild and Makefile when you open .mk file)

**What is the expected behavior?**
Let Android Studio run fine

**Please provide all relevant details.**
There is an issue reported on Makefile page https://github.com/kropp/intellij-makefile/issues/191
Either DockDockBuild or makefile should at least handle this conflict with a warning because i'm sure some users have both Makefile support and DockDockBuild installed even they don't know and they will get stuck with this issue for too long time
It had took me an hour to help my friend solve this problem with Android Studio

**Comment by virustripple** [comment]
we can not explain it to ourselves, after the update and took over and adapting the data, the mod no longer starts on the phone.
no matter what you do. no start function and game does not start.
ask for your help.
old function works without problems
just start picture comes. but nothing else
![received_827359871386840](https://user-images.githubusercontent.com/74042018/100144011-76522880-2e96-11eb-92cd-4d9626efb451.jpeg)

**Comment by HilaG** [comment]
This can happen because DockDockBuild is was created from Makefile Support and has the same class names.
I was planning on an update and changing that but I'm a little short on time now.
I'll fix this as soon as I can.

Thanks!
